name: Build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'README*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      name: Set up JDK 17
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'
        cache-dependency-path: '**/pom.xml'

    - name: Build with Maven
      run: |
        mvn -version
        mvn formatter:validate verify --file pom.xml
